DROP TABLE users CASCADE;
DROP TABLE caregivers CASCADE;
DROP TABLE members CASCADE;
DROP TABLE addresses CASCADE;
DROP TABLE jobs CASCADE;
DROP TABLE job_applications CASCADE;
DROP TABLE appointments CASCADE;